"""with specified table names

Revision ID: 216511edcd06
Revises: 
Create Date: 2024-09-14 21:31:33.347877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216511edcd06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yogacourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('instructor', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['yogacourse.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.drop_table('yoga_course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yoga_course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('instructor', sa.VARCHAR(length=50), nullable=False),
    sa.Column('booked_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['booked_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bookings')
    op.drop_table('yogacourse')
    # ### end Alembic commands ###
