"""participant fix

Revision ID: 9034b69ac97f
Revises: 9c8cdbb2d0d1
Create Date: 2024-09-18 11:58:16.085697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9034b69ac97f'
down_revision = '9c8cdbb2d0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yogacourse', schema=None) as batch_op:
        batch_op.alter_column('current_participants',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yogacourse', schema=None) as batch_op:
        batch_op.alter_column('current_participants',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
